FROM inkeister/spark-base:0.1.0

ENV SPARK_APPLICATION_JAR_NAME Docker-Maven-Template-0.1.0-SNAPSHOT
ENV SPARK_APPLICATION_MAIN_CLASS eu.bde.template.maven.WordCount
ENV SPARK_APPLICATION_ARGS "/spark/README.md"
